version: '3.8'

services:
  dairy-db:
    image: mysql:8.0
    container_name: dairy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dairy_db
    ports:
      - "3308:3306"
    volumes:
      - dairy_mysql_data:/var/lib/mysql

volumes:
  dairy_mysql_data:
